### ISSUE TITLE
Support HTML tags as delimiters

### ISSUE THREAD

**Issue by xuhdev** [Fanael/rainbow-delimiters#28] opened 2016-12-02 08:37 UTC
Hight light HTML/XML tags as delimiters are very interesting -- they are very helpful for editing these types of files.

Original proposal: http://emacs.stackexchange.com/questions/17183/is-there-a-plugin-that-does-color-html-matching-tags-like-rainbow-delimiters

**Comment by Fanael** [comment] 2016-12-02 08:38
Duplicate of #27.

**Closed by Fanael** 2016-12-02 08:38 UTC
