### ISSUE TITLE
Not working in web files such as html?

### ISSUE THREAD

**Issue by c02y** [Fanael/rainbow-delimiters#27] opened 2016-11-10 07:36 UTC
https://emacs.stackexchange.com/questions/17183/is-there-a-plugin-that-does-color-html-matching-tags-like-rainbow-delimiters

**Comment by Fanael** [comment] 2016-11-10 09:23
I'm not sure what the problem is supposed to be. `rainbow-delimiters` doesn't highlight HTML tags because that's not what it's for.

It should be possible to highlight HTML tag pairs, but that requires some help from the major mode (especially considering void elements and optional closing tags) – and I don't want any major-mode specific code in `rainbow-delimiters`, so it'd have to be a separate package.

If there's a generic way to find the bounds of some generic block (e.g. a pair of parentheses, `begin`..`end` (compare #20) or a pair of HTML tags), I'm not aware of it.

**Closed by Fanael** 2016-11-10 09:23 UTC
